apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
      - name: myappvpromc
        image: memcachd
        ports:
          - name: vpromc-port
            containerPort: 11211
